import { ModelCategory, OnlineChatModel, ImageGenerationModel, OfflineChatModelCatalogItem } from './types';

export const MODEL_CATEGORIES: ModelCategory[] = [
  { id: 'general', label: 'General AI', description: 'Everyday chat, reasoning, summarization, planning.', icon: '✨' },
  { id: 'coding', label: 'Coding', description: 'Code writing, debugging, refactoring, API help.', icon: '💻' },
  { id: 'math', label: 'Math / Study', description: 'Step-by-step learning, formulas, proofs, exam prep.', icon: '📐' },
  { id: 'business', label: 'Business', description: 'Emails, strategy, proposals, marketing, workflows.', icon: '💼' },
  { id: 'law', label: 'Law', description: 'Legal drafting and research assistance, not legal advice.', icon: '⚖️' },
  { id: 'medical', label: 'Medical', description: 'Medical-domain models for educational use, not diagnosis.', icon: '🩺' },
  { id: 'writing', label: 'Writing', description: 'Polishing, storytelling, rewriting, content creation.', icon: '✍️' },
  { id: 'small-fast', label: 'Small / Fast', description: 'Low RAM, quick tests, older laptops.', icon: '⚡' },
  { id: 'large-quality', label: 'Large / Quality', description: 'Higher quality when RAM and time are available.', icon: '🧠' },
  { id: 'vision', label: 'Vision', description: 'Image/photo understanding when supported by model/provider.', icon: '👁️' },
  { id: 'image-realistic', label: 'Realistic Image', description: 'Photorealistic image generation models.', icon: '📷' },
  { id: 'image-art', label: 'Art / Anime', description: 'Illustration, anime, concept art, stylized output.', icon: '🎨' },
  { id: 'image-design', label: 'Design / Product', description: 'Marketing creatives, product shots, posters, logos.', icon: '🧩' },
];

export const OFFLINE_CHAT_CATALOG: OfflineChatModelCatalogItem[] = [
  {
    id: 'tinyllama-q4',
    name: 'TinyLlama 1.1B Chat',
    params: '1.1B', quant: 'Q4_K_M', size: '0.7 GB', ram: '2 GB', speed: 'Very fast', quality: 'Basic',
    categories: ['general', 'small-fast'],
    recommendedUse: 'Fast smoke tests, low-RAM laptops, basic chat.',
    url: 'https://huggingface.co/TheBloke/TinyLlama-1.1B-Chat-v1.0-GGUF/resolve/main/tinyllama-1.1b-chat-v1.0.Q4_K_M.gguf?download=true',
  },
  {
    id: 'qwen25-15b-instruct-q4',
    name: 'Qwen2.5 1.5B Instruct',
    params: '1.5B', quant: 'Q4_K_M', size: '1.0 GB', ram: '3 GB', speed: 'Very fast', quality: 'Good for size',
    categories: ['general', 'coding', 'math', 'small-fast'],
    recommendedUse: 'Fast general chat, coding help, study prompts.',
    url: 'https://huggingface.co/Qwen/Qwen2.5-1.5B-Instruct-GGUF/resolve/main/qwen2.5-1.5b-instruct-q4_k_m.gguf?download=true',
  },
  {
    id: 'phi3-mini-q4',
    name: 'Phi-3 Mini 4K Instruct',
    params: '3.8B', quant: 'Q4', size: '2.2 GB', ram: '6 GB', speed: 'Fast', quality: 'Good',
    categories: ['general', 'coding', 'math', 'small-fast'],
    recommendedUse: 'Balanced first real model for laptops.',
    url: 'https://huggingface.co/microsoft/Phi-3-mini-4k-instruct-gguf/resolve/main/Phi-3-mini-4k-instruct-q4.gguf?download=true',
  },
  {
    id: 'mistral-7b-instruct-q4',
    name: 'Mistral 7B Instruct v0.2',
    params: '7B', quant: 'Q4_K_M', size: '4.4 GB', ram: '8 GB', speed: 'Medium', quality: 'Strong',
    categories: ['general', 'business', 'writing', 'large-quality'],
    recommendedUse: 'Professional writing, business answers, general assistant use.',
    url: 'https://huggingface.co/TheBloke/Mistral-7B-Instruct-v0.2-GGUF/resolve/main/mistral-7b-instruct-v0.2.Q4_K_M.gguf?download=true',
  },
  {
    id: 'llama3-8b-instruct-q4',
    name: 'Llama 3 8B Instruct',
    params: '8B', quant: 'Q4_K_M', size: '4.9 GB', ram: '10 GB', speed: 'Medium', quality: 'Strong',
    categories: ['general', 'writing', 'business', 'large-quality'],
    recommendedUse: 'Higher-quality general assistant when enough RAM is available.',
    url: 'https://huggingface.co/QuantFactory/Meta-Llama-3-8B-Instruct-GGUF/resolve/main/Meta-Llama-3-8B-Instruct.Q4_K_M.gguf?download=true',
  },
  {
    id: 'qwen25-coder-7b-q4',
    name: 'Qwen2.5 Coder 7B Instruct',
    params: '7B', quant: 'Q4_K_M', size: '4.7 GB', ram: '8 GB', speed: 'Medium', quality: 'Strong coding',
    categories: ['coding', 'large-quality'],
    recommendedUse: 'Code generation, debugging, API integrations, scripts.',
    url: 'https://huggingface.co/Qwen/Qwen2.5-Coder-7B-Instruct-GGUF/resolve/main/qwen2.5-coder-7b-instruct-q4_k_m.gguf?download=true',
  },
  {
    id: 'qwen25-math-7b-q4',
    name: 'Qwen2.5 Math 7B Instruct',
    params: '7B', quant: 'Q4_K_M', size: '4.7 GB', ram: '8 GB', speed: 'Medium', quality: 'Strong math',
    categories: ['math', 'large-quality'],
    recommendedUse: 'Math explanations, proofs, problem solving, study workflows.',
    url: 'https://huggingface.co/Qwen/Qwen2.5-Math-7B-Instruct-GGUF/resolve/main/qwen2.5-math-7b-instruct-q4_k_m.gguf?download=true',
  },
  {
    id: 'biomistral-7b-q4',
    name: 'BioMistral 7B',
    params: '7B', quant: 'Q4_K_M', size: '4.4 GB', ram: '8 GB', speed: 'Medium', quality: 'Medical domain',
    categories: ['medical', 'large-quality'],
    recommendedUse: 'Medical-domain educational Q&A. Not a diagnosis tool.',
    url: '',
  },

  {
    id: 'openhermes-mistral-7b-q4',
    name: 'OpenHermes 2.5 Mistral 7B',
    params: '7B', quant: 'Q4_K_M', size: '4.4 GB', ram: '8 GB', speed: 'Medium', quality: 'Strong instruction',
    categories: ['general', 'writing', 'business', 'large-quality'],
    recommendedUse: 'Friendly general assistant, writing, roleplay-style personas, and business drafting.',
    url: '',
  },
  {
    id: 'neural-chat-7b-q4',
    name: 'Intel Neural Chat 7B',
    params: '7B', quant: 'Q4_K_M', size: '4.1 GB', ram: '8 GB', speed: 'Medium', quality: 'Good chat',
    categories: ['general', 'writing', 'small-fast'],
    recommendedUse: 'Reliable general chat and writing on average laptops.',
    url: '',
  },
  {
    id: 'deepseek-coder-67b-q4',
    name: 'DeepSeek Coder 6.7B Instruct',
    params: '6.7B', quant: 'Q4_K_M', size: '3.8 GB', ram: '8 GB', speed: 'Medium', quality: 'Strong coding',
    categories: ['coding', 'small-fast'],
    recommendedUse: 'Offline coding, bug fixing, API integration help, and code review.',
    url: '',
  },
  {
    id: 'sqlcoder-7b-q4',
    name: 'SQLCoder 7B',
    params: '7B', quant: 'Q4_K_M', size: '4.0 GB', ram: '8 GB', speed: 'Medium', quality: 'SQL specialist',
    categories: ['coding', 'business'],
    recommendedUse: 'SQL query generation, database explanations, and analytics workflows.',
    url: '',
  },
  {
    id: 'wizardmath-7b-q4',
    name: 'WizardMath 7B',
    params: '7B', quant: 'Q4_K_M', size: '4.0 GB', ram: '8 GB', speed: 'Medium', quality: 'Math specialist',
    categories: ['math', 'large-quality'],
    recommendedUse: 'Offline math practice, exam explanations, and symbolic reasoning.',
    url: '',
  },
  {
    id: 'nous-capybara-7b-q4',
    name: 'Nous Capybara 7B',
    params: '7B', quant: 'Q4_K_M', size: '4.2 GB', ram: '8 GB', speed: 'Medium', quality: 'Good assistant',
    categories: ['general', 'writing', 'business'],
    recommendedUse: 'General assistant, structured responses, and professional writing.',
    url: '',
  },
  {
    id: 'law-chat-7b-q4',
    name: 'Law / Legal Chat 7B',
    params: '7B', quant: 'Q4_K_M', size: '4–5 GB', ram: '8 GB', speed: 'Medium', quality: 'Legal domain',
    categories: ['law', 'business'],
    recommendedUse: 'Legal drafting assistance and study. Not legal advice.',
    url: '',
  },

  {
    id: 'mixtral-8x7b-q4',
    name: 'Mixtral 8x7B Instruct',
    params: '46.7B', quant: 'Q4_K_M', size: '26–30 GB', ram: '32–48 GB', speed: 'Heavy', quality: 'High',
    categories: ['general', 'business', 'writing', 'large-quality'],
    recommendedUse: 'Enterprise-grade local assistant use on high-RAM workstations or CPU+GPU split systems.',
    url: '',
  },
  {
    id: 'qwen25-32b-instruct-q4',
    name: 'Qwen2.5 32B Instruct',
    params: '32B', quant: 'Q4_K_M', size: '18–22 GB', ram: '32 GB+', speed: 'Heavy', quality: 'Very high',
    categories: ['general', 'coding', 'math', 'business', 'large-quality'],
    recommendedUse: 'High-quality local reasoning, coding, math, and business analysis for professional hardware.',
    url: '',
  },
  {
    id: 'qwen25-coder-32b-q4',
    name: 'Qwen2.5 Coder 32B Instruct',
    params: '32B', quant: 'Q4_K_M', size: '18–22 GB', ram: '32 GB+', speed: 'Heavy', quality: 'Excellent coding',
    categories: ['coding', 'large-quality'],
    recommendedUse: 'Enterprise local coding assistant for repositories, debugging, refactoring, and software architecture.',
    url: '',
  },
  {
    id: 'llama31-70b-instruct-q4',
    name: 'Llama 3.1 70B Instruct',
    params: '70B', quant: 'Q4_K_M', size: '40–48 GB', ram: '64 GB+', speed: 'Very heavy', quality: 'Enterprise',
    categories: ['general', 'business', 'writing', 'law', 'large-quality'],
    recommendedUse: 'Large local assistant for organizations with strong CPU RAM and high-VRAM or multi-GPU systems.',
    url: '',
  },
  {
    id: 'llama31-70b-instruct-q5',
    name: 'Llama 3.1 70B Instruct High Quality',
    params: '70B', quant: 'Q5_K_M', size: '48–56 GB', ram: '80 GB+', speed: 'Very heavy', quality: 'Higher fidelity',
    categories: ['general', 'business', 'writing', 'large-quality'],
    recommendedUse: 'Higher-quality 70B local deployment for organizations with qualified enterprise hardware.',
    url: '',
  },
  {
    id: 'deepseek-coder-33b-q4',
    name: 'DeepSeek Coder 33B Instruct',
    params: '33B', quant: 'Q4_K_M', size: '18–22 GB', ram: '32 GB+', speed: 'Heavy', quality: 'Excellent coding',
    categories: ['coding', 'large-quality'],
    recommendedUse: 'Large local coding model for enterprise development teams and code review workflows.',
    url: '',
  },
];

export const ONLINE_CHAT_MODELS: OnlineChatModel[] = [
  {
    id: 'groq-llama-3.1-8b-instant', provider: 'groq', providerName: 'Groq', modelId: 'llama-3.1-8b-instant',
    name: 'Llama 3.1 8B Instant', tier: 'free', speed: 'Extremely fast', quality: 'Good',
    categories: ['general', 'small-fast'], recommendedUse: 'Fast free-tier chat and app testing.', requiresApiKey: true, apiKeyUrl: 'https://console.groq.com/keys',
  },
  {
    id: 'groq-llama-3.3-70b-versatile', provider: 'groq', providerName: 'Groq', modelId: 'llama-3.3-70b-versatile',
    name: 'Llama 3.3 70B Versatile', tier: 'free', speed: 'Very fast', quality: 'High',
    categories: ['general', 'business', 'writing', 'large-quality'], recommendedUse: 'High-quality free-tier chat where Groq access is available.', requiresApiKey: true, apiKeyUrl: 'https://console.groq.com/keys',
  },
  {
    id: 'groq-qwen-qwq-32b', provider: 'groq', providerName: 'Groq', modelId: 'qwen-qwq-32b',
    name: 'Qwen QwQ 32B', tier: 'free', speed: 'Fast', quality: 'Reasoning',
    categories: ['math', 'coding', 'large-quality'], recommendedUse: 'Reasoning-heavy coding and math prompts.', requiresApiKey: true, apiKeyUrl: 'https://console.groq.com/keys',
  },
  {
    id: 'gemini-15-flash', provider: 'gemini', providerName: 'Google Gemini', modelId: 'gemini-1.5-flash',
    name: 'Gemini 1.5 Flash', tier: 'free', speed: 'Fast', quality: 'Good',
    categories: ['general', 'vision', 'writing'], recommendedUse: 'Free-tier online chat and multimodal workflows later.', requiresApiKey: true, apiKeyUrl: 'https://aistudio.google.com/app/apikey',
  },
  {
    id: 'gemini-25-flash', provider: 'gemini', providerName: 'Google Gemini', modelId: 'gemini-2.5-flash',
    name: 'Gemini 2.5 Flash', tier: 'free', speed: 'Fast', quality: 'High',
    categories: ['general', 'coding', 'math', 'vision'], recommendedUse: 'Strong free-tier reasoning and coding when available.', requiresApiKey: true, apiKeyUrl: 'https://aistudio.google.com/app/apikey',
  },
  {
    id: 'openrouter-qwen-72b', provider: 'openrouter', providerName: 'OpenRouter', modelId: 'qwen/qwen-2.5-72b-instruct',
    name: 'Qwen 2.5 72B Instruct', tier: 'premium', speed: 'Provider dependent', quality: 'Very high',
    categories: ['general', 'coding', 'math', 'large-quality'], recommendedUse: 'Premium high-quality reasoning through OpenRouter.', requiresApiKey: true, apiKeyUrl: 'https://openrouter.ai/keys',
  },
  {
    id: 'openrouter-deepseek-chat', provider: 'openrouter', providerName: 'OpenRouter', modelId: 'deepseek/deepseek-chat',
    name: 'DeepSeek Chat', tier: 'premium', speed: 'Provider dependent', quality: 'Strong',
    categories: ['coding', 'business', 'general'], recommendedUse: 'Coding and professional chat through OpenRouter.', requiresApiKey: true, apiKeyUrl: 'https://openrouter.ai/keys',
  },

  {
    id: 'openrouter-claude-sonnet', provider: 'openrouter', providerName: 'OpenRouter', modelId: 'anthropic/claude-sonnet-4',
    name: 'Claude Sonnet via OpenRouter', tier: 'premium', speed: 'Provider dependent', quality: 'Very high',
    categories: ['general', 'coding', 'business', 'writing', 'large-quality'], recommendedUse: 'Premium planning, coding, writing, and complex reasoning through OpenRouter.', requiresApiKey: true, apiKeyUrl: 'https://openrouter.ai/keys',
  },
  {
    id: 'openrouter-gemini-pro', provider: 'openrouter', providerName: 'OpenRouter', modelId: 'google/gemini-pro-1.5',
    name: 'Gemini Pro via OpenRouter', tier: 'premium', speed: 'Provider dependent', quality: 'High',
    categories: ['general', 'vision', 'math', 'large-quality'], recommendedUse: 'Premium multimodal-capable workflows and long context tasks through OpenRouter.', requiresApiKey: true, apiKeyUrl: 'https://openrouter.ai/keys',
  },
  {
    id: 'deepseek-reasoner', provider: 'deepseek', providerName: 'DeepSeek', modelId: 'deepseek-reasoner',
    name: 'DeepSeek Reasoner', tier: 'premium', speed: 'Provider dependent', quality: 'Reasoning',
    categories: ['coding', 'math', 'large-quality'], recommendedUse: 'Reasoning-heavy coding, algorithms, and math with a DeepSeek API key.', requiresApiKey: true, apiKeyUrl: 'https://platform.deepseek.com/api_keys',
  },
  {
    id: 'mistral-large', provider: 'mistral', providerName: 'Mistral AI', modelId: 'mistral-large-latest',
    name: 'Mistral Large', tier: 'premium', speed: 'Fast', quality: 'High',
    categories: ['general', 'business', 'writing', 'law', 'large-quality'], recommendedUse: 'Professional premium writing, business, and structured reasoning with a Mistral API key.', requiresApiKey: true, apiKeyUrl: 'https://console.mistral.ai/api-keys/',
  },
  {
    id: 'together-mixtral', provider: 'together', providerName: 'Together AI', modelId: 'mistralai/Mixtral-8x7B-Instruct-v0.1',
    name: 'Mixtral 8x7B Instruct', tier: 'premium', speed: 'Fast', quality: 'High',
    categories: ['general', 'business', 'writing', 'large-quality'], recommendedUse: 'Premium general and business chat.', requiresApiKey: true, apiKeyUrl: 'https://api.together.xyz/settings/api-keys',
  },
  {
    id: 'together-qwen-coder', provider: 'together', providerName: 'Together AI', modelId: 'Qwen/Qwen2.5-Coder-32B-Instruct',
    name: 'Qwen2.5 Coder 32B', tier: 'premium', speed: 'Fast', quality: 'Excellent coding',
    categories: ['coding', 'large-quality'], recommendedUse: 'Premium coding and software engineering.', requiresApiKey: true, apiKeyUrl: 'https://api.together.xyz/settings/api-keys',
  },
];

export const IMAGE_GENERATION_MODELS: ImageGenerationModel[] = [
  {
    id: 'pollinations-flux', type: 'image', mode: 'online', tier: 'free', provider: 'pollinations', providerName: 'Pollinations', modelId: 'flux',
    name: 'Pollinations FLUX', categories: ['image-realistic', 'image-art', 'image-design'],
    recommendedUse: 'Free online image generation with no API key. Good for quick prototypes.', requiresApiKey: false, supportsDirectGeneration: true,
    defaultWidth: 1024, defaultHeight: 1024,
  },
  {
    id: 'pollinations-turbo', type: 'image', mode: 'online', tier: 'free', provider: 'pollinations', providerName: 'Pollinations', modelId: 'turbo',
    name: 'Pollinations Turbo', categories: ['image-design', 'image-art'],
    recommendedUse: 'Fast free online drafts, posters, thumbnails, and social creatives.', requiresApiKey: false, supportsDirectGeneration: true,
    defaultWidth: 768, defaultHeight: 768,
  },
  {
    id: 'hf-sdxl', type: 'image', mode: 'online', tier: 'free', provider: 'huggingface', providerName: 'Hugging Face', modelId: 'stabilityai/stable-diffusion-xl-base-1.0',
    name: 'SDXL via Hugging Face', categories: ['image-realistic', 'image-art'],
    recommendedUse: 'Free/free-tier image generation when Hugging Face Inference is available.', requiresApiKey: true, supportsDirectGeneration: false,
    defaultWidth: 1024, defaultHeight: 1024,
  },
  {
    id: 'together-flux-schnell', type: 'image', mode: 'online', tier: 'premium', provider: 'together', providerName: 'Together AI', modelId: 'black-forest-labs/FLUX.1-schnell',
    name: 'FLUX.1 Schnell', categories: ['image-realistic', 'image-design'],
    recommendedUse: 'Premium fast high-quality images through Together AI.', requiresApiKey: true, supportsDirectGeneration: false,
    defaultWidth: 1024, defaultHeight: 1024,
  },
  {
    id: 'stability-sdxl', type: 'image', mode: 'online', tier: 'premium', provider: 'stability', providerName: 'Stability AI', modelId: 'stable-image-core',
    name: 'Stability Image Core / SDXL', categories: ['image-realistic', 'image-design'],
    recommendedUse: 'Premium production-quality images with a Stability AI key.', requiresApiKey: true, supportsDirectGeneration: false,
    defaultWidth: 1024, defaultHeight: 1024,
  },

  {
    id: 'replicate-flux-dev', type: 'image', mode: 'online', tier: 'premium', provider: 'replicate', providerName: 'Replicate', modelId: 'black-forest-labs/flux-dev',
    name: 'FLUX Dev via Replicate', categories: ['image-realistic', 'image-design'],
    recommendedUse: 'Premium high-quality prompt-to-image workflows through Replicate.', requiresApiKey: true, supportsDirectGeneration: false,
    defaultWidth: 1024, defaultHeight: 1024,
  },
  {
    id: 'offline-sd-turbo', type: 'image', mode: 'offline', tier: 'free', provider: 'local', providerName: 'Local SD Turbo', modelId: 'sd-turbo',
    name: 'SD Turbo Local', categories: ['image-design', 'image-art'],
    recommendedUse: 'Fast offline draft images once local image runtime is wired.', requiresApiKey: false, supportsDirectGeneration: false,
    defaultWidth: 512, defaultHeight: 512,
  },
  {
    id: 'offline-sd15', type: 'image', mode: 'offline', tier: 'free', provider: 'local', providerName: 'Local Stable Diffusion', modelId: 'sd15',
    name: 'Stable Diffusion 1.5 Local', categories: ['image-art', 'image-design'],
    recommendedUse: 'Offline image generation on modest hardware after local runtime support is installed.', requiresApiKey: false, supportsDirectGeneration: false,
    defaultWidth: 512, defaultHeight: 512,
  },
  {
    id: 'offline-sdxl', type: 'image', mode: 'offline', tier: 'free', provider: 'local', providerName: 'Local SDXL', modelId: 'sdxl',
    name: 'SDXL Local', categories: ['image-realistic', 'image-art', 'image-design'],
    recommendedUse: 'Offline high-quality image generation on stronger GPUs.', requiresApiKey: false, supportsDirectGeneration: false,
    defaultWidth: 1024, defaultHeight: 1024,
  },
  {
    id: 'offline-flux-schnell', type: 'image', mode: 'offline', tier: 'free', provider: 'local', providerName: 'Local FLUX', modelId: 'flux-schnell',
    name: 'FLUX Schnell Local', categories: ['image-realistic', 'image-design'],
    recommendedUse: 'Offline next-gen image generation on high-VRAM systems after runtime support.', requiresApiKey: false, supportsDirectGeneration: false,
    defaultWidth: 1024, defaultHeight: 1024,
  },
];
