import { ModelCategory, OnlineChatModel, ImageGenerationModel, OfflineChatModelCatalogItem } from './types';

export const MODEL_CATEGORIES: ModelCategory[] = [
  { id: 'general', label: 'General AI', description: 'Everyday chat, reasoning, summarization, planning.', icon: '✨' },
  { id: 'coding', label: 'Coding', description: 'Code writing, debugging, refactoring, API help.', icon: '💻' },
  { id: 'math', label: 'Math / Study', description: 'Step-by-step learning, formulas, proofs, exam prep.', icon: '📐' },
  { id: 'business', label: 'Business', description: 'Emails, strategy, proposals, marketing, workflows.', icon: '💼' },
  { id: 'law', label: 'Law', description: 'Legal drafting and research assistance, not legal advice.', icon: '⚖️' },
  { id: 'medical', label: 'Medical', description: 'Medical-domain models for educational use, not diagnosis.', icon: '🩺' },
  { id: 'writing', label: 'Writing', description: 'Polishing, storytelling, rewriting, content creation.', icon: '✍️' },
  { id: 'small-fast', label: 'Small / Fast', description: 'Low RAM, quick tests, older laptops.', icon: '⚡' },
  { id: 'large-quality', label: 'Large / Quality', description: 'Higher quality when RAM and time are available.', icon: '🧠' },
  { id: 'vision', label: 'Vision', description: 'Image/photo understanding when supported by model/provider.', icon: '👁️' },
  { id: 'image-realistic', label: 'Realistic Image', description: 'Photorealistic image generation models.', icon: '📷' },
  { id: 'image-art', label: 'Art / Anime', description: 'Illustration, anime, concept art, stylized output.', icon: '🎨' },
  { id: 'image-design', label: 'Design / Product', description: 'Marketing creatives, product shots, posters, logos.', icon: '🧩' },
];

/** Build primary + remaining shard URLs for Hugging Face split GGUFs. */
function hfGgufShards(
  repo: string,
  folder: string,
  fileBase: string,
  shardCount: number,
): { url: string; shardUrls: string[] } {
  const pad = (n: number) => String(n).padStart(5, '0');
  const of = pad(shardCount);
  const mk = (i: number) =>
    `https://huggingface.co/${repo}/resolve/main/${folder}/${fileBase}-${pad(i)}-of-${of}.gguf?download=true`;
  return {
    url: mk(1),
    shardUrls: Array.from({ length: Math.max(0, shardCount - 1) }, (_, i) => mk(i + 2)),
  };
}

const DEEPSEEK_V3_Q2 = hfGgufShards(
  'unsloth/DeepSeek-V3-0324-GGUF',
  'UD-Q2_K_XL',
  'DeepSeek-V3-0324-UD-Q2_K_XL',
  6,
);
const MINIMAX_M3_IQ1 = hfGgufShards(
  'unsloth/MiniMax-M3-GGUF',
  'UD-IQ1_M',
  'MiniMax-M3-UD-IQ1_M',
  4,
);
const QWEN35_397B_Q4 = hfGgufShards(
  'unsloth/Qwen3.5-397B-A17B-GGUF',
  'UD-Q4_K_XL',
  'Qwen3.5-397B-A17B-UD-Q4_K_XL',
  6,
);
const KIMI_K26_Q2 = hfGgufShards(
  'unsloth/Kimi-K2.6-GGUF',
  'UD-Q2_K_XL',
  'Kimi-K2.6-UD-Q2_K_XL',
  8,
);
const GLM52_IQ2 = hfGgufShards(
  'unsloth/GLM-5.2-GGUF',
  'UD-IQ2_M',
  'GLM-5.2-UD-IQ2_M',
  6,
);
const DEEPSEEK_V4_PRO_Q2 = hfGgufShards(
  'teamblobfish/DeepSeek-V4-Pro-GGUF',
  'Q2_K-XL',
  'DeepSeek-V4-Pro-Q2_K-XL',
  13,
);
const DEEPSEEK_V4_FLASH_Q4 = hfGgufShards(
  'teamblobfish/DeepSeek-V4-Flash-GGUF',
  'Q4_K_M-XL',
  'DeepSeek-V4-Flash-Q4_K_M-XL',
  4,
);
const QWEN3_CODER_480B_Q2 = hfGgufShards(
  'unsloth/Qwen3-Coder-480B-A35B-Instruct-GGUF',
  'UD-Q2_K_XL',
  'Qwen3-Coder-480B-A35B-Instruct-UD-Q2_K_XL',
  4,
);
const LLAMA4_MAVERICK_Q2 = hfGgufShards(
  'unsloth/Llama-4-Maverick-17B-128E-Instruct-GGUF',
  'UD-Q2_K_XL',
  'Llama-4-Maverick-17B-128E-Instruct-UD-Q2_K_XL',
  4,
);

export const OFFLINE_CHAT_CATALOG: OfflineChatModelCatalogItem[] = [
  // ── Frontier MoE (compete with online DeepSeek / Claude / GPT class) ───────
  {
    id: 'kimi-k3-offline-pending',
    name: 'Kimi K3 (open weights pending)',
    params: '2800B', quant: 'TBD', size: 'Weights not public yet', ram: 'Multi-node / 64+ accelerators', speed: 'Server', quality: 'Open frontier champion',
    categories: ['coding', 'general', 'vision', 'math', 'large-quality'],
    recommendedUse: 'Moonshot Kimi K3 (~2.8T, 1M ctx, native vision) — open weights scheduled ~2026-07-27. Until then use Online → Kimi K3 (OpenRouter). After weights drop, import GGUF+mmproj or re-download from Models.',
    url: '',
    visionCapable: true,
  },
  {
    id: 'glm-52-ud-iq2',
    name: 'GLM-5.2',
    params: '753B', quant: 'UD-IQ2_M', size: '~6× shards (~245 GB)', ram: '245 GB+', speed: 'Server', quality: 'Frontier agentic coding',
    categories: ['coding', 'general', 'math', 'business', 'large-quality'],
    recommendedUse: 'Z.ai GLM-5.2 (753B MoE / ~40B active, 1M ctx) for long-horizon agentic coding (SWE-bench class). 6 GGUF shards. Prefer Online GLM-5.2 if you lack cluster RAM.',
    url: GLM52_IQ2.url,
    shardUrls: GLM52_IQ2.shardUrls,
  },
  {
    id: 'deepseek-v4-pro-q2xl',
    name: 'DeepSeek V4 Pro',
    params: '1600B', quant: 'Q2_K-XL', size: '~13× shards (~498 GB)', ram: '512 GB+', speed: 'Server', quality: 'Frontier Think-mode coding',
    categories: ['coding', 'general', 'math', 'large-quality'],
    recommendedUse: 'DeepSeek V4 Pro (1.6T / ~49B active, Think modes). 13 GGUF shards — requires a V4-aware llama.cpp fork (not stock upstream). Prefer Online DeepSeek V4 Pro for most users.',
    url: DEEPSEEK_V4_PRO_Q2.url,
    shardUrls: DEEPSEEK_V4_PRO_Q2.shardUrls,
  },
  {
    id: 'deepseek-v4-flash-q4xl',
    name: 'DeepSeek V4 Flash',
    params: '284B', quant: 'Q4_K_M-XL', size: '~4× shards (~163 GB)', ram: '180 GB+', speed: 'Server', quality: 'Strong V4 coding (smaller)',
    categories: ['coding', 'general', 'math', 'large-quality'],
    recommendedUse: 'More runnable DeepSeek V4 sibling (284B / ~13B active). Same V4-aware llama.cpp requirement as V4 Pro. Good offline step-up from V3.',
    url: DEEPSEEK_V4_FLASH_Q4.url,
    shardUrls: DEEPSEEK_V4_FLASH_Q4.shardUrls,
  },
  {
    id: 'qwen3-coder-480b-ud-q2',
    name: 'Qwen3 Coder 480B-A35B',
    params: '480B', quant: 'UD-Q2_K_XL', size: '~4× shards (~180 GB)', ram: '200 GB+', speed: 'Server', quality: 'Flagship agentic coding',
    categories: ['coding', 'large-quality'],
    recommendedUse: 'Alibaba Qwen3-Coder flagship (480B MoE / 35B active, 256K–1M ctx) for repository-scale offline PocketCode. 4 GGUF shards.',
    url: QWEN3_CODER_480B_Q2.url,
    shardUrls: QWEN3_CODER_480B_Q2.shardUrls,
  },
  {
    id: 'llama4-maverick-ud-q2',
    name: 'Llama 4 Maverick 17B-128E',
    params: '400B', quant: 'UD-Q2_K_XL', size: '~4× shards + mmproj (~151 GB)', ram: '160 GB+', speed: 'Server', quality: 'Native multimodal MoE',
    categories: ['vision', 'coding', 'general', 'large-quality'],
    recommendedUse: 'Meta Llama 4 Maverick (~400B MoE / 17B active, 128 experts) with early-fusion vision + huge context. 4 shards + mmproj-BF16.',
    url: LLAMA4_MAVERICK_Q2.url,
    shardUrls: LLAMA4_MAVERICK_Q2.shardUrls,
    mmprojUrl: 'https://huggingface.co/unsloth/Llama-4-Maverick-17B-128E-Instruct-GGUF/resolve/main/mmproj-BF16.gguf?download=true',
    visionCapable: true,
  },
  {
    id: 'deepseek-v3-0324-ud-q2',
    name: 'DeepSeek V3-0324',
    params: '671B', quant: 'UD-Q2_K_XL', size: '~6× shards (~248 GB)', ram: '180 GB+', speed: 'Server', quality: 'Frontier MoE coding/reasoning',
    categories: ['coding', 'general', 'math', 'large-quality'],
    recommendedUse: 'Direct offline competitor to online DeepSeek (671B MoE / ~37B active). Text+tools/PocketCode on multi-GPU / high-RAM servers. Not a native VLM — pair with a VL model for screenshots.',
    url: DEEPSEEK_V3_Q2.url,
    shardUrls: DEEPSEEK_V3_Q2.shardUrls,
  },
  {
    id: 'minimax-m3-ud-iq1',
    name: 'MiniMax M3',
    params: '428B', quant: 'UD-IQ1_M', size: '~4× shards (~128 GB)', ram: '133 GB+', speed: 'Server', quality: 'Frontier MoE multimodal',
    categories: ['vision', 'coding', 'general', 'large-quality'],
    recommendedUse: 'Native multimodal MoE (428B / ~23B active, 1M context). Downloads 4 GGUF shards. Requires recent/experimental llama.cpp MiniMax-M3 support; keep all shards together.',
    url: MINIMAX_M3_IQ1.url,
    shardUrls: MINIMAX_M3_IQ1.shardUrls,
    visionCapable: true,
  },
  {
    id: 'qwen35-397b-a17b-ud-q4',
    name: 'Qwen3.5 397B-A17B',
    params: '397B', quant: 'UD-Q4_K_XL', size: '~6× shards + mmproj (~214 GB)', ram: '256 GB+', speed: 'Server', quality: 'Frontier MoE vision',
    categories: ['vision', 'coding', 'general', 'math', 'large-quality'],
    recommendedUse: 'Qwen flagship MoE VLM (397B / ~17B active) — strongest offline alternative to DeepSeek for charts/PDFs/math-from-images. 6 shards + mmproj.',
    url: QWEN35_397B_Q4.url,
    shardUrls: QWEN35_397B_Q4.shardUrls,
    mmprojUrl: 'https://huggingface.co/Serpen/Minimax_M3_MMPROJ_GGUF/resolve/main/M3-mmproj.gguf?download=true',
    visionCapable: true,
  },
  {
    id: 'kimi-k26-ud-q2',
    name: 'Kimi K2.6',
    params: '1000B', quant: 'UD-Q2_K_XL', size: '~8× shards + mmproj (~350 GB)', ram: '350 GB+', speed: 'Server', quality: 'Frontier MoE agentic vision',
    categories: ['vision', 'coding', 'general', 'large-quality'],
    recommendedUse: 'Moonshot Kimi K2.6 (~1T sparse MoE) with native vision mmproj for screenshots/UI/layouts. 8 shards + mmproj; server-class RAM/VRAM required. Closest offline stand-in until K3 weights publish.',
    url: KIMI_K26_Q2.url,
    shardUrls: KIMI_K26_Q2.shardUrls,
    mmprojUrl: 'https://huggingface.co/unsloth/Kimi-K2.6-GGUF/resolve/main/mmproj-F16.gguf?download=true',
    visionCapable: true,
  },
  // ── Server-class offline VL (100B+ / frontier MoE) ─────────────────────────
  {
    id: 'qwen3-vl-235b-a22b-ud-q2',
    name: 'Qwen3-VL 235B-A22B Instruct',
    params: '235B', quant: 'UD-Q2_K_XL', size: '~2× shards + mmproj (~80–100 GB)', ram: '96 GB+', speed: 'Server', quality: 'Frontier MoE vision',
    categories: ['vision', 'coding', 'general', 'large-quality'],
    recommendedUse: 'DeepSeek-class open MoE VLM (235B total / ~22B active). Downloads 2 GGUF shards + mmproj. Needs multi-GPU / high unified memory; keep all shards + mmproj in the same folder.',
    url: 'https://huggingface.co/unsloth/Qwen3-VL-235B-A22B-Instruct-GGUF/resolve/main/UD-Q2_K_XL/Qwen3-VL-235B-A22B-Instruct-UD-Q2_K_XL-00001-of-00002.gguf?download=true',
    shardUrls: [
      'https://huggingface.co/unsloth/Qwen3-VL-235B-A22B-Instruct-GGUF/resolve/main/UD-Q2_K_XL/Qwen3-VL-235B-A22B-Instruct-UD-Q2_K_XL-00002-of-00002.gguf?download=true',
    ],
    mmprojUrl: 'https://huggingface.co/unsloth/Qwen3-VL-235B-A22B-Instruct-GGUF/resolve/main/mmproj-F16.gguf?download=true',
    visionCapable: true,
  },
  {
    id: 'qwen3-vl-235b-a22b-q4',
    name: 'Qwen3-VL 235B-A22B Instruct Q4',
    params: '235B', quant: 'Q4_K_M', size: '~3× shards + mmproj (~142 GB)', ram: '160 GB+', speed: 'Server', quality: 'Highest open MoE vision',
    categories: ['vision', 'coding', 'general', 'large-quality'],
    recommendedUse: 'Official Qwen Q4 MoE VLM shards (higher fidelity than Q2). Multi-GPU / DGX-class RAM. Select the 00001 shard after download; llama.cpp loads the rest.',
    url: 'https://huggingface.co/Qwen/Qwen3-VL-235B-A22B-Instruct-GGUF/resolve/main/Qwen3VL-235B-A22B-Instruct-Q4_K_M-split-00001-of-00003.gguf?download=true',
    shardUrls: [
      'https://huggingface.co/Qwen/Qwen3-VL-235B-A22B-Instruct-GGUF/resolve/main/Qwen3VL-235B-A22B-Instruct-Q4_K_M-split-00002-of-00003.gguf?download=true',
      'https://huggingface.co/Qwen/Qwen3-VL-235B-A22B-Instruct-GGUF/resolve/main/Qwen3VL-235B-A22B-Instruct-Q4_K_M-split-00003-of-00003.gguf?download=true',
    ],
    mmprojUrl: 'https://huggingface.co/Qwen/Qwen3-VL-235B-A22B-Instruct-GGUF/resolve/main/mmproj-Qwen3VL-235B-A22B-Instruct-Q8_0.gguf?download=true',
    visionCapable: true,
  },
  {
    id: 'qwen35-122b-a10b-iq3',
    name: 'Qwen3.5 122B-A10B (InstinctRazor)',
    params: '122B', quant: 'IQ3_XXS', size: '~52 GB + mmproj', ram: '80 GB+', speed: 'Server', quality: 'Frontier 100B+ vision MoE',
    categories: ['vision', 'coding', 'general', 'large-quality'],
    recommendedUse: 'True 100B+ offline VLM (122B MoE / ~10B active) with native mmproj. Best fit for multi-GPU workstations; requires recent llama.cpp with qwen3.5_moe.',
    url: 'https://huggingface.co/General-Instinct/InstinctRazor-Qwen3.5-122B-A10B-GGUF/resolve/main/InstinctRazor-Qwen3.5-122B-A10B-IQ3_XXS.gguf?download=true',
    mmprojUrl: 'https://huggingface.co/General-Instinct/InstinctRazor-Qwen3.5-122B-A10B-GGUF/resolve/main/InstinctRazor-Qwen3.5-122B-A10B-mmproj-f16.gguf?download=true',
    visionCapable: true,
  },
  {
    id: 'qwen25-vl-72b-instruct-q4',
    name: 'Qwen2.5-VL 72B Instruct',
    params: '72B', quant: 'Q4_K_M', size: '~47 GB + mmproj', ram: '64 GB+', speed: 'Slow', quality: 'Excellent dense vision',
    categories: ['vision', 'coding', 'general', 'large-quality'],
    recommendedUse: 'Strongest dense offline VLM that fits a single high-end workstation. Screenshots, PDFs, UI → code. Downloads GGUF + mmproj.',
    url: 'https://huggingface.co/bartowski/Qwen_Qwen2.5-VL-72B-Instruct-GGUF/resolve/main/Qwen_Qwen2.5-VL-72B-Instruct-Q4_K_M.gguf?download=true',
    mmprojUrl: 'https://huggingface.co/bartowski/Qwen_Qwen2.5-VL-72B-Instruct-GGUF/resolve/main/mmproj-Qwen_Qwen2.5-VL-72B-Instruct-f16.gguf?download=true',
    visionCapable: true,
  },
  {
    id: 'qwen3-vl-30b-a3b-instruct-q4',
    name: 'Qwen3-VL 30B-A3B Instruct',
    params: '30B', quant: 'Q4_K_M', size: '~18 GB + mmproj', ram: '40 GB', speed: 'Medium-slow', quality: 'Strong MoE vision',
    categories: ['vision', 'coding', 'general', 'large-quality'],
    recommendedUse: 'PocketCode-eligible MoE VLM (30B total / ~3B active). Much stronger than 7B VL for real tasks; downloads GGUF + mmproj.',
    url: 'https://huggingface.co/unsloth/Qwen3-VL-30B-A3B-Instruct-GGUF/resolve/main/Qwen3-VL-30B-A3B-Instruct-Q4_K_M.gguf?download=true',
    mmprojUrl: 'https://huggingface.co/unsloth/Qwen3-VL-30B-A3B-Instruct-GGUF/resolve/main/mmproj-F16.gguf?download=true',
    visionCapable: true,
  },
  // ── Mid / laptop offline VL ────────────────────────────────────────────────
  {
    id: 'qwen25-vl-32b-instruct-q4',
    name: 'Qwen2.5-VL 32B Instruct',
    params: '32B', quant: 'Q4_K_M', size: '~20 GB + mmproj', ram: '40 GB', speed: 'Slow', quality: 'Excellent vision + coding',
    categories: ['vision', 'coding', 'general', 'large-quality'],
    recommendedUse: 'Dense 32B offline multimodal for PocketCode. Needs substantial RAM/VRAM; downloads GGUF + mmproj.',
    url: 'https://huggingface.co/bartowski/Qwen_Qwen2.5-VL-32B-Instruct-GGUF/resolve/main/Qwen_Qwen2.5-VL-32B-Instruct-Q4_K_M.gguf?download=true',
    mmprojUrl: 'https://huggingface.co/bartowski/Qwen_Qwen2.5-VL-32B-Instruct-GGUF/resolve/main/mmproj-Qwen_Qwen2.5-VL-32B-Instruct-f16.gguf?download=true',
    visionCapable: true,
  },
  {
    id: 'qwen25-vl-7b-instruct-q4',
    name: 'Qwen2.5-VL 7B Instruct',
    params: '7B', quant: 'Q4_K_M', size: '~5 GB + mmproj', ram: '14 GB', speed: 'Medium', quality: 'Strong vision',
    categories: ['vision', 'general', 'coding', 'large-quality'],
    recommendedUse: 'Laptop-friendly offline vision smoke tests. Prefer ≥20B VL for real PocketCode work.',
    url: 'https://huggingface.co/bartowski/Qwen_Qwen2.5-VL-7B-Instruct-GGUF/resolve/main/Qwen_Qwen2.5-VL-7B-Instruct-Q4_K_M.gguf?download=true',
    mmprojUrl: 'https://huggingface.co/bartowski/Qwen_Qwen2.5-VL-7B-Instruct-GGUF/resolve/main/mmproj-Qwen_Qwen2.5-VL-7B-Instruct-f16.gguf?download=true',
    visionCapable: true,
  },
  {
    id: 'qwen2-vl-7b-instruct-q4',
    name: 'Qwen2-VL 7B Instruct',
    params: '7B', quant: 'Q4_K_M', size: '~4.7 GB + mmproj', ram: '12 GB', speed: 'Medium', quality: 'Strong vision',
    categories: ['vision', 'general', 'coding', 'small-fast'],
    recommendedUse: 'Older Qwen2-VL 7B for light offline vision when RAM is limited.',
    url: 'https://huggingface.co/bartowski/Qwen2-VL-7B-Instruct-GGUF/resolve/main/Qwen2-VL-7B-Instruct-Q4_K_M.gguf?download=true',
    mmprojUrl: 'https://huggingface.co/bartowski/Qwen2-VL-7B-Instruct-GGUF/resolve/main/mmproj-Qwen2-VL-7B-Instruct-f16.gguf?download=true',
    visionCapable: true,
  },
  {
    id: 'qwen2-vl-2b-instruct-q4',
    name: 'Qwen2-VL 2B Instruct',
    params: '2B', quant: 'Q4_K_M', size: '~1.8 GB + mmproj', ram: '6 GB', speed: 'Fast', quality: 'Basic vision',
    categories: ['vision', 'general', 'small-fast'],
    recommendedUse: 'Tiny offline vision smoke test only — not for real PocketCode tasks.',
    url: 'https://huggingface.co/bartowski/Qwen2-VL-2B-Instruct-GGUF/resolve/main/Qwen2-VL-2B-Instruct-Q4_K_M.gguf?download=true',
    mmprojUrl: 'https://huggingface.co/bartowski/Qwen2-VL-2B-Instruct-GGUF/resolve/main/mmproj-Qwen2-VL-2B-Instruct-f16.gguf?download=true',
    visionCapable: true,
  },
  {
    id: 'llava-16-mistral-7b-q4',
    name: 'LLaVA 1.6 Mistral 7B',
    params: '7B', quant: 'Q4_K_M', size: '~4.4 GB + mmproj', ram: '12 GB', speed: 'Medium', quality: 'Legacy vision',
    categories: ['vision', 'general', 'coding', 'small-fast'],
    recommendedUse: 'Classic LLaVA multimodal. Prefer Qwen2.5-VL / Qwen3-VL for quality.',
    url: 'https://huggingface.co/cjpais/llava-1.6-mistral-7b-gguf/resolve/main/llava-v1.6-mistral-7b.Q4_K_M.gguf?download=true',
    mmprojUrl: 'https://huggingface.co/cjpais/llava-1.6-mistral-7b-gguf/resolve/main/mmproj-model-f16.gguf?download=true',
    visionCapable: true,
  },
  {
    id: 'qwen25-coder-14b-q4',
    name: 'Qwen2.5 Coder 14B Instruct',
    params: '14B', quant: 'Q4_K_M', size: '~8.5 GB', ram: '16 GB', speed: 'Medium', quality: 'Excellent coding',
    categories: ['coding', 'large-quality'],
    recommendedUse: 'Strong offline coding assistant when you have mid-range RAM/VRAM.',
    url: 'https://huggingface.co/bartowski/Qwen2.5-Coder-14B-Instruct-GGUF/resolve/main/Qwen2.5-Coder-14B-Instruct-Q4_K_M.gguf?download=true',
  },
  {
    id: 'qwen25-coder-32b-q4',
    name: 'Qwen2.5 Coder 32B Instruct',
    params: '32B', quant: 'Q4_K_M', size: '~19 GB', ram: '32 GB', speed: 'Slower', quality: 'Excellent coding',
    categories: ['coding', 'large-quality'],
    recommendedUse: 'High-end offline coding GGUF for serious local PocketCode workstations.',
    url: 'https://huggingface.co/bartowski/Qwen2.5-Coder-32B-Instruct-GGUF/resolve/main/Qwen2.5-Coder-32B-Instruct-Q4_K_M.gguf?download=true',
  },
  {
    id: 'llama33-70b-instruct-q4',
    name: 'Llama 3.3 70B Instruct',
    params: '70B', quant: 'Q4_K_M', size: '~40 GB', ram: '48 GB+', speed: 'Slow', quality: 'Frontier local',
    categories: ['general', 'coding', 'business', 'writing', 'large-quality'],
    recommendedUse: 'PocketCode-eligible offline 70B-class general/coding model (needs serious hardware).',
    url: 'https://huggingface.co/bartowski/Llama-3.3-70B-Instruct-GGUF/resolve/main/Llama-3.3-70B-Instruct-Q4_K_M.gguf?download=true',
  },
  {
    id: 'tinyllama-q4',
    name: 'TinyLlama 1.1B Chat',
    params: '1.1B', quant: 'Q4_K_M', size: '0.7 GB', ram: '2 GB', speed: 'Very fast', quality: 'Basic',
    categories: ['general', 'small-fast'],
    recommendedUse: 'Fast smoke tests, low-RAM laptops, basic chat.',
    url: 'https://huggingface.co/TheBloke/TinyLlama-1.1B-Chat-v1.0-GGUF/resolve/main/tinyllama-1.1b-chat-v1.0.Q4_K_M.gguf?download=true',
  },
  {
    id: 'qwen25-15b-instruct-q4',
    name: 'Qwen2.5 1.5B Instruct',
    params: '1.5B', quant: 'Q4_K_M', size: '1.0 GB', ram: '3 GB', speed: 'Very fast', quality: 'Good for size',
    categories: ['general', 'coding', 'math', 'small-fast'],
    recommendedUse: 'Fast general chat, coding help, study prompts.',
    url: 'https://huggingface.co/Qwen/Qwen2.5-1.5B-Instruct-GGUF/resolve/main/qwen2.5-1.5b-instruct-q4_k_m.gguf?download=true',
  },
  {
    id: 'phi3-mini-q4',
    name: 'Phi-3 Mini 4K Instruct',
    params: '3.8B', quant: 'Q4', size: '2.2 GB', ram: '6 GB', speed: 'Fast', quality: 'Good',
    categories: ['general', 'coding', 'math', 'small-fast'],
    recommendedUse: 'Balanced first real model for laptops.',
    url: 'https://huggingface.co/microsoft/Phi-3-mini-4k-instruct-gguf/resolve/main/Phi-3-mini-4k-instruct-q4.gguf?download=true',
  },
  {
    id: 'mistral-7b-instruct-q4',
    name: 'Mistral 7B Instruct v0.2',
    params: '7B', quant: 'Q4_K_M', size: '4.4 GB', ram: '8 GB', speed: 'Medium', quality: 'Strong',
    categories: ['general', 'business', 'writing', 'large-quality'],
    recommendedUse: 'Professional writing, business answers, general assistant use.',
    url: 'https://huggingface.co/TheBloke/Mistral-7B-Instruct-v0.2-GGUF/resolve/main/mistral-7b-instruct-v0.2.Q4_K_M.gguf?download=true',
  },
  {
    id: 'llama3-8b-instruct-q4',
    name: 'Llama 3 8B Instruct',
    params: '8B', quant: 'Q4_K_M', size: '4.9 GB', ram: '10 GB', speed: 'Medium', quality: 'Strong',
    categories: ['general', 'writing', 'business', 'large-quality'],
    recommendedUse: 'Higher-quality general assistant when enough RAM is available.',
    url: 'https://huggingface.co/QuantFactory/Meta-Llama-3-8B-Instruct-GGUF/resolve/main/Meta-Llama-3-8B-Instruct.Q4_K_M.gguf?download=true',
  },
  {
    id: 'qwen25-coder-7b-q4',
    name: 'Qwen2.5 Coder 7B Instruct',
    params: '7B', quant: 'Q4_K_M', size: '4.7 GB', ram: '8 GB', speed: 'Medium', quality: 'Strong coding',
    categories: ['coding', 'large-quality'],
    recommendedUse: 'Code generation, debugging, API integrations, scripts.',
    url: 'https://huggingface.co/Qwen/Qwen2.5-Coder-7B-Instruct-GGUF/resolve/main/qwen2.5-coder-7b-instruct-q4_k_m.gguf?download=true',
  },
  {
    id: 'qwen25-math-7b-q4',
    name: 'Qwen2.5 Math 7B Instruct',
    params: '7B', quant: 'Q4_K_M', size: '4.7 GB', ram: '8 GB', speed: 'Medium', quality: 'Strong math',
    categories: ['math', 'large-quality'],
    recommendedUse: 'Math explanations, proofs, problem solving, study workflows.',
    url: 'https://huggingface.co/Qwen/Qwen2.5-Math-7B-Instruct-GGUF/resolve/main/qwen2.5-math-7b-instruct-q4_k_m.gguf?download=true',
  },
  {
    id: 'biomistral-7b-q4',
    name: 'BioMistral 7B',
    params: '7B', quant: 'Q4_K_M', size: '4.4 GB', ram: '8 GB', speed: 'Medium', quality: 'Medical domain',
    categories: ['medical', 'large-quality'],
    recommendedUse: 'Medical-domain educational Q&A. Not a diagnosis tool.',
    url: 'https://huggingface.co/QuantFactory/BioMistral-7B-GGUF/resolve/main/BioMistral-7B.Q4_K_M.gguf?download=true',
  },

  {
    id: 'openhermes-mistral-7b-q4',
    name: 'OpenHermes 2.5 Mistral 7B',
    params: '7B', quant: 'Q4_K_M', size: '4.4 GB', ram: '8 GB', speed: 'Medium', quality: 'Strong instruction',
    categories: ['general', 'writing', 'business', 'large-quality'],
    recommendedUse: 'Friendly general assistant, writing, roleplay-style personas, and business drafting.',
    url: 'https://huggingface.co/TheBloke/OpenHermes-2.5-Mistral-7B-GGUF/resolve/main/openhermes-2.5-mistral-7b.Q4_K_M.gguf?download=true',
  },
  {
    id: 'neural-chat-7b-q4',
    name: 'Intel Neural Chat 7B',
    params: '7B', quant: 'Q4_K_M', size: '4.1 GB', ram: '8 GB', speed: 'Medium', quality: 'Good chat',
    categories: ['general', 'writing', 'small-fast'],
    recommendedUse: 'Reliable general chat and writing on average laptops.',
    url: 'https://huggingface.co/TheBloke/neural-chat-7b-v3-1-GGUF/resolve/main/neural-chat-7b-v3-1.Q4_K_M.gguf?download=true',
  },
  {
    id: 'deepseek-coder-67b-q4',
    name: 'DeepSeek Coder 6.7B Instruct',
    params: '6.7B', quant: 'Q4_K_M', size: '3.8 GB', ram: '8 GB', speed: 'Medium', quality: 'Strong coding',
    categories: ['coding', 'small-fast'],
    recommendedUse: 'Offline coding, bug fixing, API integration help, and code review.',
    url: 'https://huggingface.co/TheBloke/deepseek-coder-6.7B-instruct-GGUF/resolve/main/deepseek-coder-6.7b-instruct.Q4_K_M.gguf?download=true',
  },
  {
    id: 'sqlcoder-7b-q4',
    name: 'SQLCoder 7B',
    params: '7B', quant: 'Q4_K_M', size: '4.0 GB', ram: '8 GB', speed: 'Medium', quality: 'SQL specialist',
    categories: ['coding', 'business'],
    recommendedUse: 'SQL query generation, database explanations, and analytics workflows.',
    url: 'https://huggingface.co/TheBloke/sqlcoder-7b-GGUF/resolve/main/sqlcoder-7b.Q4_K_M.gguf?download=true',
  },
  {
    id: 'wizardmath-7b-q4',
    name: 'WizardMath 7B',
    params: '7B', quant: 'Q4_K_M', size: '4.0 GB', ram: '8 GB', speed: 'Medium', quality: 'Math specialist',
    categories: ['math', 'large-quality'],
    recommendedUse: 'Offline math practice, exam explanations, and symbolic reasoning.',
    url: 'https://huggingface.co/TheBloke/WizardMath-7B-V1.1-GGUF/resolve/main/wizardmath-7b-v1.1.Q4_K_M.gguf?download=true',
  },
  {
    id: 'nous-capybara-7b-q4',
    name: 'Nous Capybara 7B',
    params: '7B', quant: 'Q4_K_M', size: '4.2 GB', ram: '8 GB', speed: 'Medium', quality: 'Good assistant',
    categories: ['general', 'writing', 'business'],
    recommendedUse: 'General assistant, structured responses, and professional writing.',
    url: 'https://huggingface.co/TheBloke/Nous-Capybara-7B-v1.9-GGUF/resolve/main/nous-capybara-7b-v1.9.Q4_K_M.gguf?download=true',
  },
  {
    id: 'law-chat-7b-q4',
    name: 'Law / Legal Chat 7B',
    params: '7B', quant: 'Q4_K_M', size: '4–5 GB', ram: '8 GB', speed: 'Medium', quality: 'Legal domain',
    categories: ['law', 'business'],
    recommendedUse: 'Legal drafting assistance and study. Not legal advice.',
    url: 'https://huggingface.co/TheBloke/law-chat-GGUF/resolve/main/law-chat.Q4_K_M.gguf?download=true',
  },

  {
    id: 'mixtral-8x7b-q4',
    name: 'Mixtral 8x7B Instruct',
    params: '46.7B', quant: 'Q4_K_M', size: '26–30 GB', ram: '32–48 GB', speed: 'Heavy', quality: 'High',
    categories: ['general', 'business', 'writing', 'large-quality'],
    recommendedUse: 'Enterprise-grade local assistant use on high-RAM workstations or CPU+GPU split systems.',
    url: 'https://huggingface.co/TheBloke/Mixtral-8x7B-Instruct-v0.1-GGUF/resolve/main/mixtral-8x7b-instruct-v0.1.Q4_K_M.gguf?download=true',
  },
  {
    id: 'qwen25-32b-instruct-q4',
    name: 'Qwen2.5 32B Instruct',
    params: '32B', quant: 'Q4_K_M', size: '18–22 GB', ram: '32 GB+', speed: 'Heavy', quality: 'Very high',
    categories: ['general', 'coding', 'math', 'business', 'large-quality'],
    recommendedUse: 'High-quality local reasoning, coding, math, and business analysis for professional hardware.',
    url: 'https://huggingface.co/bartowski/Qwen2.5-32B-Instruct-GGUF/resolve/main/Qwen2.5-32B-Instruct-Q4_K_M.gguf?download=true',
  },
  {
    id: 'llama31-70b-instruct-q4',
    name: 'Llama 3.1 70B Instruct',
    params: '70B', quant: 'Q4_K_M', size: '40–48 GB', ram: '64 GB+', speed: 'Very heavy', quality: 'Enterprise',
    categories: ['general', 'business', 'writing', 'law', 'large-quality'],
    recommendedUse: 'Large local assistant for organizations with strong CPU RAM and high-VRAM or multi-GPU systems.',
    url: 'https://huggingface.co/bartowski/Meta-Llama-3.1-70B-Instruct-GGUF/resolve/main/Meta-Llama-3.1-70B-Instruct-Q4_K_M.gguf?download=true',
  },
  {
    id: 'llama31-70b-instruct-q5',
    name: 'Llama 3.1 70B Instruct High Quality',
    params: '70B', quant: 'Q5_K_M', size: '48–56 GB', ram: '80 GB+', speed: 'Very heavy', quality: 'Higher fidelity',
    categories: ['general', 'business', 'writing', 'large-quality'],
    recommendedUse: 'Higher-quality 70B local deployment for organizations with qualified enterprise hardware.',
    url: 'https://huggingface.co/mradermacher/Meta-Llama-3.1-70B-Instruct-GGUF/resolve/main/Meta-Llama-3.1-70B-Instruct.Q5_K_M.gguf?download=true',
  },
  {
    id: 'deepseek-coder-33b-q4',
    name: 'DeepSeek Coder 33B Instruct',
    params: '33B', quant: 'Q4_K_M', size: '18–22 GB', ram: '32–48 GB', speed: 'Heavy', quality: 'Excellent coding',
    categories: ['coding', 'large-quality'],
    recommendedUse: 'Large local coding model for enterprise development teams and code review workflows.',
    url: 'https://huggingface.co/TheBloke/deepseek-coder-33b-instruct-GGUF/resolve/main/deepseek-coder-33b-instruct.Q4_K_M.gguf?download=true',
  },
  {
    id: 'qwen25-72b-instruct-q4',
    name: 'Qwen2.5 72B Instruct',
    params: '72B', quant: 'Q4_K_M', size: '40–48 GB', ram: '64 GB+', speed: 'Very heavy', quality: 'Enterprise',
    categories: ['general', 'coding', 'math', 'business', 'large-quality'],
    recommendedUse: 'Strong multilingual reasoning and coding on qualified enterprise hardware. Code Workspace eligible.',
    url: 'https://huggingface.co/bartowski/Qwen2.5-72B-Instruct-GGUF/resolve/main/Qwen2.5-72B-Instruct-Q4_K_M.gguf?download=true',
  },
  {
    id: 'command-r-plus-104b-q4',
    name: 'Command R+ 104B',
    params: '104B', quant: 'Q4_K_M', size: '55–65 GB', ram: '96 GB+', speed: 'Very heavy', quality: 'Enterprise RAG',
    categories: ['general', 'business', 'writing', 'large-quality'],
    recommendedUse: 'Long-context enterprise assistant / RAG workflows on multi-GPU servers. Code Workspace eligible.',
    url: 'https://huggingface.co/bartowski/c4ai-command-r-plus-GGUF/resolve/main/c4ai-command-r-plus-Q4_K_M.gguf/c4ai-command-r-plus-Q4_K_M-00001-of-00006.gguf?download=true',
shardUrls: [
      'https://huggingface.co/bartowski/c4ai-command-r-plus-GGUF/resolve/main/c4ai-command-r-plus-Q4_K_M.gguf/c4ai-command-r-plus-Q4_K_M-00002-of-00006.gguf?download=true',
      'https://huggingface.co/bartowski/c4ai-command-r-plus-GGUF/resolve/main/c4ai-command-r-plus-Q4_K_M.gguf/c4ai-command-r-plus-Q4_K_M-00003-of-00006.gguf?download=true',
      'https://huggingface.co/bartowski/c4ai-command-r-plus-GGUF/resolve/main/c4ai-command-r-plus-Q4_K_M.gguf/c4ai-command-r-plus-Q4_K_M-00004-of-00006.gguf?download=true',
      'https://huggingface.co/bartowski/c4ai-command-r-plus-GGUF/resolve/main/c4ai-command-r-plus-Q4_K_M.gguf/c4ai-command-r-plus-Q4_K_M-00005-of-00006.gguf?download=true',
      'https://huggingface.co/bartowski/c4ai-command-r-plus-GGUF/resolve/main/c4ai-command-r-plus-Q4_K_M.gguf/c4ai-command-r-plus-Q4_K_M-00006-of-00006.gguf?download=true',
    ],  },
  {
    id: 'mixtral-8x22b-q4',
    name: 'Mixtral 8x22B Instruct',
    params: '141B', quant: 'Q4_K_M', size: '70–90 GB', ram: '128 GB+', speed: 'Extreme', quality: 'Enterprise MoE',
    categories: ['general', 'coding', 'business', 'large-quality'],
    recommendedUse: 'Sparse MoE local deployment for teams with large VRAM pools. Code Workspace eligible.',
    url: 'https://huggingface.co/MaziyarPanahi/Mixtral-8x22B-Instruct-v0.1-GGUF/resolve/main/Mixtral-8x22B-Instruct-v0.1.Q4_K_M-00001-of-00002.gguf?download=true',
shardUrls: [
      'https://huggingface.co/MaziyarPanahi/Mixtral-8x22B-Instruct-v0.1-GGUF/resolve/main/Mixtral-8x22B-Instruct-v0.1.Q4_K_M-00002-of-00002.gguf?download=true',
    ],  },
  {
    id: 'llama31-405b-instruct-q4',
    name: 'Llama 3.1 405B Instruct',
    params: '405B', quant: 'Q4_K_M', size: '200–240 GB', ram: '256 GB+ / multi-GPU', speed: 'Extreme', quality: 'Frontier local',
    categories: ['general', 'coding', 'math', 'business', 'writing', 'law', 'large-quality'],
    recommendedUse: 'Frontier-class local GGUF for clusters / high-end servers. Import a quantized .gguf (often multi-part). Code Workspace eligible.',
    url: 'https://huggingface.co/bullerwins/Meta-Llama-3.1-405B-Instruct-GGUF/resolve/main/Meta-Llama-3.1-405B-Instruct-Q4_K_M-00001-of-00006.gguf?download=true',
shardUrls: [
      'https://huggingface.co/bullerwins/Meta-Llama-3.1-405B-Instruct-GGUF/resolve/main/Meta-Llama-3.1-405B-Instruct-Q4_K_M-00002-of-00006.gguf?download=true',
      'https://huggingface.co/bullerwins/Meta-Llama-3.1-405B-Instruct-GGUF/resolve/main/Meta-Llama-3.1-405B-Instruct-Q4_K_M-00003-of-00006.gguf?download=true',
      'https://huggingface.co/bullerwins/Meta-Llama-3.1-405B-Instruct-GGUF/resolve/main/Meta-Llama-3.1-405B-Instruct-Q4_K_M-00004-of-00006.gguf?download=true',
      'https://huggingface.co/bullerwins/Meta-Llama-3.1-405B-Instruct-GGUF/resolve/main/Meta-Llama-3.1-405B-Instruct-Q4_K_M-00005-of-00006.gguf?download=true',
      'https://huggingface.co/bullerwins/Meta-Llama-3.1-405B-Instruct-GGUF/resolve/main/Meta-Llama-3.1-405B-Instruct-Q4_K_M-00006-of-00006.gguf?download=true',
    ],  },
  {
    id: 'llama31-405b-instruct-q5',
    name: 'Llama 3.1 405B Instruct High Quality',
    params: '405B', quant: 'Q5_K_M', size: '250–300 GB', ram: '320 GB+ / multi-GPU', speed: 'Extreme', quality: 'Frontier fidelity',
    categories: ['general', 'coding', 'business', 'large-quality'],
    recommendedUse: 'Higher-fidelity 405B local deployment when you have the cluster budget. Code Workspace eligible.',
    url: 'https://huggingface.co/bullerwins/Meta-Llama-3.1-405B-Instruct-GGUF/resolve/main/Meta-Llama-3.1-405B-Instruct-Q5_K_M-00001-of-00007.gguf?download=true',
shardUrls: [
      'https://huggingface.co/bullerwins/Meta-Llama-3.1-405B-Instruct-GGUF/resolve/main/Meta-Llama-3.1-405B-Instruct-Q5_K_M-00002-of-00007.gguf?download=true',
      'https://huggingface.co/bullerwins/Meta-Llama-3.1-405B-Instruct-GGUF/resolve/main/Meta-Llama-3.1-405B-Instruct-Q5_K_M-00003-of-00007.gguf?download=true',
      'https://huggingface.co/bullerwins/Meta-Llama-3.1-405B-Instruct-GGUF/resolve/main/Meta-Llama-3.1-405B-Instruct-Q5_K_M-00004-of-00007.gguf?download=true',
      'https://huggingface.co/bullerwins/Meta-Llama-3.1-405B-Instruct-GGUF/resolve/main/Meta-Llama-3.1-405B-Instruct-Q5_K_M-00005-of-00007.gguf?download=true',
      'https://huggingface.co/bullerwins/Meta-Llama-3.1-405B-Instruct-GGUF/resolve/main/Meta-Llama-3.1-405B-Instruct-Q5_K_M-00006-of-00007.gguf?download=true',
      'https://huggingface.co/bullerwins/Meta-Llama-3.1-405B-Instruct-GGUF/resolve/main/Meta-Llama-3.1-405B-Instruct-Q5_K_M-00007-of-00007.gguf?download=true',
    ],  },
];

export const ONLINE_CHAT_MODELS: OnlineChatModel[] = [
  {
    id: 'groq-gpt-oss-20b', provider: 'groq', providerName: 'Groq', modelId: 'openai/gpt-oss-20b',
    name: 'GPT OSS 20B', tier: 'free', speed: 'Extremely fast', quality: 'Good',
    categories: ['general', 'small-fast', 'coding'], recommendedUse: 'Current Groq free-tier replacement for Llama 3.1 Instant.', requiresApiKey: true, apiKeyUrl: 'https://console.groq.com/keys',
  },
  {
    id: 'groq-gpt-oss-120b', provider: 'groq', providerName: 'Groq', modelId: 'openai/gpt-oss-120b',
    name: 'GPT OSS 120B', tier: 'free', speed: 'Very fast', quality: 'High',
    categories: ['general', 'business', 'writing', 'coding', 'large-quality'], recommendedUse: 'Current Groq free-tier 120B-class chat and coding.', requiresApiKey: true, apiKeyUrl: 'https://console.groq.com/keys',
  },
  {
    id: 'groq-qwen-3-6-27b', provider: 'groq', providerName: 'Groq', modelId: 'qwen/qwen3.6-27b',
    name: 'Qwen 3.6 27B', tier: 'free', speed: 'Fast', quality: 'Reasoning',
    categories: ['math', 'coding', 'large-quality'], recommendedUse: 'Groq-hosted Qwen 3.6 for reasoning-heavy coding and math.', requiresApiKey: true, apiKeyUrl: 'https://console.groq.com/keys',
  },
  {
    id: 'cerebras-gpt-oss-120b', provider: 'cerebras', providerName: 'Cerebras', modelId: 'gpt-oss-120b',
    name: 'GPT OSS 120B', tier: 'free', speed: 'Extremely fast', quality: 'Very high',
    categories: ['general', 'coding', 'business', 'writing', 'large-quality'],
    recommendedUse: 'Cerebras free-tier production model — very fast 120B-class chat and coding.',
    requiresApiKey: true, apiKeyUrl: 'https://cloud.cerebras.ai/',
  },
  {
    id: 'cerebras-gemma-4-31b', provider: 'cerebras', providerName: 'Cerebras', modelId: 'gemma-4-31b',
    name: 'Gemma 4 31B', tier: 'free', speed: 'Extremely fast', quality: 'High',
    categories: ['general', 'coding', 'writing', 'large-quality'],
    recommendedUse: 'Cerebras preview Gemma 4 31B for fast free-tier chat and coding eval.',
    requiresApiKey: true, apiKeyUrl: 'https://cloud.cerebras.ai/',
  },
  {
    id: 'cerebras-zai-glm-4-7', provider: 'cerebras', providerName: 'Cerebras', modelId: 'zai-glm-4.7',
    name: 'Z.ai GLM 4.7', tier: 'free', speed: 'Very fast', quality: 'Reasoning',
    categories: ['coding', 'math', 'general', 'large-quality'],
    recommendedUse: 'Cerebras preview GLM 4.7 for reasoning-heavy coding and math (preview; may change).',
    requiresApiKey: true, apiKeyUrl: 'https://cloud.cerebras.ai/',
  },
  {
    id: 'gemini-38-flash', provider: 'gemini', providerName: 'Google Gemini', modelId: 'gemini-3.8-flash',
    name: 'Gemini 3.8 Flash', tier: 'free', speed: 'Fast', quality: 'High',
    categories: ['general', 'coding', 'math', 'vision'], recommendedUse: 'Current Gemini Flash for free-tier chat, coding, and vision.', requiresApiKey: true, apiKeyUrl: 'https://aistudio.google.com/app/apikey',
  },
  {
    id: 'gemini-35-flash', provider: 'gemini', providerName: 'Google Gemini', modelId: 'gemini-3.5-flash',
    name: 'Gemini 3.5 Flash', tier: 'free', speed: 'Fast', quality: 'High',
    categories: ['general', 'coding', 'vision'], recommendedUse: 'Gemini 3.5 Flash when 3.8 is not enabled on the key.', requiresApiKey: true, apiKeyUrl: 'https://aistudio.google.com/app/apikey',
  },
  {
    id: 'openrouter-qwen-72b', provider: 'openrouter', providerName: 'OpenRouter', modelId: 'qwen/qwen-2.5-72b-instruct',
    name: 'Qwen 2.5 72B Instruct', tier: 'premium', speed: 'Provider dependent', quality: 'Very high',
    categories: ['general', 'coding', 'math', 'large-quality'], recommendedUse: 'Premium high-quality reasoning through OpenRouter.', requiresApiKey: true, apiKeyUrl: 'https://openrouter.ai/keys',
  },
  {
    id: 'openrouter-deepseek-chat', provider: 'openrouter', providerName: 'OpenRouter', modelId: 'deepseek/deepseek-chat',
    name: 'DeepSeek Chat', tier: 'premium', speed: 'Provider dependent', quality: 'Strong',
    categories: ['coding', 'business', 'general'], recommendedUse: 'Coding and professional chat through OpenRouter.', requiresApiKey: true, apiKeyUrl: 'https://openrouter.ai/keys',
  },

  {
    id: 'openrouter-claude-sonnet', provider: 'openrouter', providerName: 'OpenRouter', modelId: 'anthropic/claude-sonnet-4',
    name: 'Claude Sonnet via OpenRouter', tier: 'premium', speed: 'Provider dependent', quality: 'Very high',
    categories: ['general', 'coding', 'business', 'writing', 'vision', 'large-quality'], recommendedUse: 'Premium planning, coding, writing, vision, and complex reasoning through OpenRouter.', requiresApiKey: true, apiKeyUrl: 'https://openrouter.ai/keys',
  },
  {
    id: 'openrouter-gemini-pro', provider: 'openrouter', providerName: 'OpenRouter', modelId: 'google/gemini-3.8-flash',
    name: 'Gemini 3.8 Flash via OpenRouter', tier: 'premium', speed: 'Provider dependent', quality: 'High',
    categories: ['general', 'vision', 'math', 'coding', 'large-quality'], recommendedUse: 'Current Gemini Flash through OpenRouter.', requiresApiKey: true, apiKeyUrl: 'https://openrouter.ai/keys',
  },
  {
    id: 'openai-gpt-6-astra', provider: 'openai', providerName: 'OpenAI', modelId: 'gpt-6-astra',
    name: 'GPT-6 Astra', tier: 'premium', speed: 'Fast', quality: 'Frontier',
    categories: ['general', 'coding', 'business', 'writing', 'vision', 'large-quality'],
    recommendedUse: 'Current OpenAI flagship for complex professional work, coding, and vision.',
    requiresApiKey: true, apiKeyUrl: 'https://platform.openai.com/api-keys',
  },
  {
    id: 'openai-gpt-5.6-sol', provider: 'openai', providerName: 'OpenAI', modelId: 'gpt-5.6-sol',
    name: 'GPT-5.6 Sol', tier: 'premium', speed: 'Fast', quality: 'Frontier',
    categories: ['general', 'coding', 'business', 'writing', 'vision', 'large-quality'],
    recommendedUse: 'OpenAI GPT-5.6 Sol for complex professional work.',
    requiresApiKey: true, apiKeyUrl: 'https://platform.openai.com/api-keys',
  },
  {
    id: 'openai-gpt-5.5', provider: 'openai', providerName: 'OpenAI', modelId: 'gpt-5.5',
    name: 'GPT-5.5', tier: 'premium', speed: 'Fast', quality: 'Frontier',
    categories: ['general', 'coding', 'business', 'writing', 'vision', 'large-quality'],
    recommendedUse: 'OpenAI GPT-5.5 when your account still exposes this model.',
    requiresApiKey: true, apiKeyUrl: 'https://platform.openai.com/api-keys',
  },
  {
    id: 'openai-gpt-5.5-pro', provider: 'openai', providerName: 'OpenAI', modelId: 'gpt-5.5-pro',
    name: 'GPT-5.5 Pro', tier: 'premium', speed: 'Provider dependent', quality: 'Maximum',
    categories: ['general', 'coding', 'math', 'business', 'vision', 'large-quality'],
    recommendedUse: 'Maximum OpenAI GPT-5.5 Pro performance for the hardest tasks.',
    requiresApiKey: true, apiKeyUrl: 'https://platform.openai.com/api-keys',
  },
  {
    id: 'openai-gpt-5.4', provider: 'openai', providerName: 'OpenAI', modelId: 'gpt-5.4',
    name: 'GPT-5.4', tier: 'premium', speed: 'Fast', quality: 'Frontier',
    categories: ['general', 'coding', 'business', 'writing', 'vision', 'large-quality'],
    recommendedUse: 'OpenAI GPT-5.4 for strong coding, reasoning, and multimodal workflows.',
    requiresApiKey: true, apiKeyUrl: 'https://platform.openai.com/api-keys',
  },
  {
    id: 'openai-gpt-5.4-pro', provider: 'openai', providerName: 'OpenAI', modelId: 'gpt-5.4-pro',
    name: 'GPT-5.4 Pro', tier: 'premium', speed: 'Provider dependent', quality: 'Maximum',
    categories: ['general', 'coding', 'math', 'vision', 'large-quality'],
    recommendedUse: 'OpenAI GPT-5.4 Pro when you need maximum quality on complex jobs.',
    requiresApiKey: true, apiKeyUrl: 'https://platform.openai.com/api-keys',
  },
  {
    id: 'openrouter-gpt-5.5', provider: 'openrouter', providerName: 'OpenRouter', modelId: 'openai/gpt-5.5',
    name: 'GPT-5.5 via OpenRouter', tier: 'premium', speed: 'Provider dependent', quality: 'Frontier',
    categories: ['general', 'coding', 'business', 'writing', 'vision', 'large-quality'],
    recommendedUse: 'GPT-5.5 through OpenRouter when you prefer a single OpenRouter key.',
    requiresApiKey: true, apiKeyUrl: 'https://openrouter.ai/keys',
  },
  {
    id: 'openrouter-gpt-5.4', provider: 'openrouter', providerName: 'OpenRouter', modelId: 'openai/gpt-5.4',
    name: 'GPT-5.4 via OpenRouter', tier: 'premium', speed: 'Provider dependent', quality: 'Frontier',
    categories: ['general', 'coding', 'business', 'vision', 'large-quality'],
    recommendedUse: 'GPT-5.4 through OpenRouter.',
    requiresApiKey: true, apiKeyUrl: 'https://openrouter.ai/keys',
  },
  {
    id: 'anthropic-fable-5-1', provider: 'anthropic', providerName: 'Anthropic', modelId: 'claude-fable-5-1',
    name: 'Claude Fable 5.1', tier: 'premium', speed: 'Fast', quality: 'Frontier',
    categories: ['general', 'coding', 'business', 'writing', 'vision', 'large-quality'],
    recommendedUse: 'Current Anthropic Fable 5.1 for planning, coding, and vision.',
    requiresApiKey: true, apiKeyUrl: 'https://console.anthropic.com/settings/keys',
  },
  {
    id: 'anthropic-opus-5', provider: 'anthropic', providerName: 'Anthropic', modelId: 'claude-opus-5',
    name: 'Claude Opus 5', tier: 'premium', speed: 'Provider dependent', quality: 'Frontier',
    categories: ['general', 'coding', 'business', 'writing', 'vision', 'large-quality'],
    recommendedUse: 'Anthropic Claude Opus 5 flagship.',
    requiresApiKey: true, apiKeyUrl: 'https://console.anthropic.com/settings/keys',
  },
  {
    id: 'anthropic-opus-4-8', provider: 'anthropic', providerName: 'Anthropic', modelId: 'claude-opus-4-8',
    name: 'Claude Opus 4.8', tier: 'premium', speed: 'Provider dependent', quality: 'Frontier',
    categories: ['general', 'coding', 'business', 'writing', 'vision', 'large-quality'],
    recommendedUse: 'Anthropic Claude Opus 4.8 flagship for planning, coding, and vision.',
    requiresApiKey: true, apiKeyUrl: 'https://console.anthropic.com/settings/keys',
  },
  {
    id: 'anthropic-opus-4-7', provider: 'anthropic', providerName: 'Anthropic', modelId: 'claude-opus-4-7',
    name: 'Claude Opus 4.7', tier: 'premium', speed: 'Provider dependent', quality: 'Frontier',
    categories: ['general', 'coding', 'business', 'writing', 'vision', 'large-quality'],
    recommendedUse: 'Anthropic Claude Opus 4.7 for complex agentic and multimodal work.',
    requiresApiKey: true, apiKeyUrl: 'https://console.anthropic.com/settings/keys',
  },
  {
    id: 'openrouter-opus-4-8', provider: 'openrouter', providerName: 'OpenRouter', modelId: 'anthropic/claude-opus-4-8',
    name: 'Claude Opus 4.8 via OpenRouter', tier: 'premium', speed: 'Provider dependent', quality: 'Frontier',
    categories: ['general', 'coding', 'business', 'writing', 'vision', 'large-quality'],
    recommendedUse: 'Opus 4.8 through OpenRouter.',
    requiresApiKey: true, apiKeyUrl: 'https://openrouter.ai/keys',
  },
  {
    id: 'openrouter-opus-4-7', provider: 'openrouter', providerName: 'OpenRouter', modelId: 'anthropic/claude-opus-4-7',
    name: 'Claude Opus 4.7 via OpenRouter', tier: 'premium', speed: 'Provider dependent', quality: 'Frontier',
    categories: ['general', 'coding', 'business', 'writing', 'vision', 'large-quality'],
    recommendedUse: 'Opus 4.7 through OpenRouter.',
    requiresApiKey: true, apiKeyUrl: 'https://openrouter.ai/keys',
  },
  {
    id: 'anthropic-sonnet-4-6', provider: 'anthropic', providerName: 'Anthropic', modelId: 'claude-sonnet-4-6',
    name: 'Claude Sonnet 4.6', tier: 'premium', speed: 'Fast', quality: 'Very high',
    categories: ['general', 'coding', 'business', 'writing', 'vision', 'large-quality'],
    recommendedUse: 'Balanced Anthropic Sonnet 4.6 with vision for everyday coding and chat.',
    requiresApiKey: true, apiKeyUrl: 'https://console.anthropic.com/settings/keys',
  },
  {
    id: 'gemini-25-pro', provider: 'gemini', providerName: 'Google Gemini', modelId: 'gemini-2.5-pro',
    name: 'Gemini 2.5 Pro', tier: 'premium', speed: 'Fast', quality: 'Frontier',
    categories: ['general', 'coding', 'math', 'vision', 'large-quality'],
    recommendedUse: 'Google Gemini 2.5 Pro for long-context reasoning and vision.',
    requiresApiKey: true, apiKeyUrl: 'https://aistudio.google.com/app/apikey',
  },
  {
    id: 'openai-gpt-4o', provider: 'openai', providerName: 'OpenAI', modelId: 'gpt-4o',
    name: 'GPT-4o', tier: 'premium', speed: 'Fast', quality: 'Frontier',
    categories: ['general', 'coding', 'business', 'writing', 'vision', 'large-quality'],
    recommendedUse: 'Direct OpenAI GPT-4o for chat, coding, and image understanding. Requires an OpenAI API key.',
    requiresApiKey: true, apiKeyUrl: 'https://platform.openai.com/api-keys',
  },
  {
    id: 'openai-gpt-4o-mini', provider: 'openai', providerName: 'OpenAI', modelId: 'gpt-4o-mini',
    name: 'GPT-4o Mini', tier: 'premium', speed: 'Very fast', quality: 'High',
    categories: ['general', 'coding', 'vision', 'small-fast'],
    recommendedUse: 'Lower-cost OpenAI vision + chat model for screenshots and everyday multimodal work.',
    requiresApiKey: true, apiKeyUrl: 'https://platform.openai.com/api-keys',
  },
  {
    id: 'openai-gpt-4.1', provider: 'openai', providerName: 'OpenAI', modelId: 'gpt-4.1',
    name: 'GPT-4.1', tier: 'premium', speed: 'Fast', quality: 'Frontier',
    categories: ['general', 'coding', 'business', 'writing', 'vision', 'large-quality'],
    recommendedUse: 'Direct OpenAI GPT-4.1 for strong instruction following, coding, and vision.',
    requiresApiKey: true, apiKeyUrl: 'https://platform.openai.com/api-keys',
  },
  {
    id: 'anthropic-claude-sonnet', provider: 'anthropic', providerName: 'Anthropic', modelId: 'claude-sonnet-5',
    name: 'Claude Sonnet 5', tier: 'premium', speed: 'Fast', quality: 'Very high',
    categories: ['general', 'coding', 'business', 'writing', 'vision', 'large-quality'],
    recommendedUse: 'Current Anthropic Claude Sonnet 5 with vision (Messages API).',
    requiresApiKey: true, apiKeyUrl: 'https://console.anthropic.com/settings/keys',
  },
  {
    id: 'anthropic-claude-opus', provider: 'anthropic', providerName: 'Anthropic', modelId: 'claude-opus-5',
    name: 'Claude Opus 5', tier: 'premium', speed: 'Provider dependent', quality: 'Frontier',
    categories: ['general', 'coding', 'business', 'writing', 'vision', 'large-quality'],
    recommendedUse: 'Current Anthropic Claude Opus 5 with vision for complex planning and multimodal debugging.',
    requiresApiKey: true, apiKeyUrl: 'https://console.anthropic.com/settings/keys',
  },
  {
    id: 'deepseek-v4-pro', provider: 'deepseek', providerName: 'DeepSeek', modelId: 'deepseek-v4-pro',
    name: 'DeepSeek V4 Pro', tier: 'premium', speed: 'Provider dependent', quality: 'Frontier',
    categories: ['coding', 'business', 'general', 'math', 'vision', 'large-quality'],
    recommendedUse: 'DeepSeek V4 Pro via official API — strong coding, long-context agents, reasoning, and image understanding (uses your DeepSeek balance).',
    requiresApiKey: true, apiKeyUrl: 'https://platform.deepseek.com/api_keys',
  },
  {
    id: 'deepseek-v4-flash', provider: 'deepseek', providerName: 'DeepSeek', modelId: 'deepseek-v4-flash',
    name: 'DeepSeek V4 Flash', tier: 'premium', speed: 'Fast', quality: 'Strong',
    categories: ['coding', 'business', 'general', 'vision', 'large-quality'],
    recommendedUse: 'DeepSeek V4 Flash via official API — faster/cheaper chat, coding, and screenshot/image understanding with a DeepSeek API key.',
    requiresApiKey: true, apiKeyUrl: 'https://platform.deepseek.com/api_keys',
  },
  {
    id: 'deepseek-chat', provider: 'deepseek', providerName: 'DeepSeek', modelId: 'deepseek-chat',
    name: 'DeepSeek Chat (legacy)', tier: 'premium', speed: 'Fast', quality: 'Strong',
    categories: ['coding', 'business', 'general', 'vision', 'large-quality'],
    recommendedUse: 'Legacy ID (routes to V4 Flash non-thinking). Prefer DeepSeek V4 Flash / V4 Pro; legacy IDs may stop working after DeepSeek’s deprecation date.',
    requiresApiKey: true, apiKeyUrl: 'https://platform.deepseek.com/api_keys',
  },
  {
    id: 'deepseek-reasoner', provider: 'deepseek', providerName: 'DeepSeek', modelId: 'deepseek-reasoner',
    name: 'DeepSeek Reasoner (legacy)', tier: 'premium', speed: 'Provider dependent', quality: 'Reasoning',
    categories: ['coding', 'math', 'vision', 'large-quality'],
    recommendedUse: 'Legacy ID (routes to V4 Flash thinking). Prefer DeepSeek V4 Pro / V4 Flash for new work.',
    requiresApiKey: true, apiKeyUrl: 'https://platform.deepseek.com/api_keys',
  },
  {
    id: 'mistral-large', provider: 'mistral', providerName: 'Mistral AI', modelId: 'mistral-large-latest',
    name: 'Mistral Large', tier: 'premium', speed: 'Fast', quality: 'High',
    categories: ['general', 'business', 'writing', 'law', 'large-quality'], recommendedUse: 'Professional premium writing, business, and structured reasoning with a Mistral API key.', requiresApiKey: true, apiKeyUrl: 'https://console.mistral.ai/api-keys/',
  },
  {
    id: 'mistral-pixtral-large', provider: 'mistral', providerName: 'Mistral AI', modelId: 'pixtral-large-latest',
    name: 'Pixtral Large', tier: 'premium', speed: 'Fast', quality: 'High vision',
    categories: ['general', 'coding', 'vision', 'large-quality'],
    recommendedUse: 'Mistral Pixtral for screenshots, diagrams, and multimodal document pages.',
    requiresApiKey: true, apiKeyUrl: 'https://console.mistral.ai/api-keys/',
  },
  {
    id: 'gemini-20-flash', provider: 'gemini', providerName: 'Google Gemini', modelId: 'gemini-3.6-flash',
    name: 'Gemini 3.6 Flash', tier: 'free', speed: 'Fast', quality: 'High',
    categories: ['general', 'coding', 'vision', 'writing'],
    recommendedUse: 'Current Gemini 3.6 Flash for chat and image understanding with a Google AI Studio key.',
    requiresApiKey: true, apiKeyUrl: 'https://aistudio.google.com/app/apikey',
  },
  {
    id: 'openrouter-gpt-4o-mini', provider: 'openrouter', providerName: 'OpenRouter', modelId: 'openai/gpt-4o-mini',
    name: 'GPT-4o Mini via OpenRouter', tier: 'premium', speed: 'Very fast', quality: 'High',
    categories: ['general', 'coding', 'vision', 'small-fast'],
    recommendedUse: 'Lower-cost GPT-4o Mini vision through OpenRouter.',
    requiresApiKey: true, apiKeyUrl: 'https://openrouter.ai/keys',
  },
  {
    id: 'openrouter-pixtral', provider: 'openrouter', providerName: 'OpenRouter', modelId: 'mistralai/pixtral-large-2411',
    name: 'Pixtral Large via OpenRouter', tier: 'premium', speed: 'Provider dependent', quality: 'High vision',
    categories: ['general', 'coding', 'vision', 'large-quality'],
    recommendedUse: 'Mistral Pixtral vision through OpenRouter without a direct Mistral key.',
    requiresApiKey: true, apiKeyUrl: 'https://openrouter.ai/keys',
  },
  {
    id: 'together-mixtral', provider: 'together', providerName: 'Together AI', modelId: 'mistralai/Mixtral-8x7B-Instruct-v0.1',
    name: 'Mixtral 8x7B Instruct', tier: 'premium', speed: 'Fast', quality: 'High',
    categories: ['general', 'business', 'writing', 'large-quality'], recommendedUse: 'Premium general and business chat.', requiresApiKey: true, apiKeyUrl: 'https://api.together.xyz/settings/api-keys',
  },
  {
    id: 'together-qwen-coder', provider: 'together', providerName: 'Together AI', modelId: 'Qwen/Qwen2.5-Coder-32B-Instruct',
    name: 'Qwen2.5 Coder 32B', tier: 'premium', speed: 'Fast', quality: 'Excellent coding',
    categories: ['coding', 'large-quality'], recommendedUse: 'Premium coding and software engineering.', requiresApiKey: true, apiKeyUrl: 'https://api.together.xyz/settings/api-keys',
  },

  // Frontier / large models (Code Workspace eligible when selected online)
  {
    id: 'openrouter-kimi-k3', provider: 'openrouter', providerName: 'OpenRouter', modelId: 'moonshotai/kimi-k3',
    name: 'Kimi K3', tier: 'premium', speed: 'Provider dependent', quality: 'Open frontier champion',
    categories: ['coding', 'general', 'math', 'vision', 'business', 'large-quality'],
    recommendedUse: 'Moonshot Kimi K3 (~2.8T, 1M ctx, vision) via OpenRouter — best way to use K3 until open GGUF weights ship. PocketCode + screenshots.',
    requiresApiKey: true, apiKeyUrl: 'https://openrouter.ai/keys',
  },
  {
    id: 'openrouter-kimi-k26', provider: 'openrouter', providerName: 'OpenRouter', modelId: 'moonshotai/kimi-k2.6',
    name: 'Kimi K2.6 (online)', tier: 'premium', speed: 'Provider dependent', quality: 'Frontier agentic',
    categories: ['coding', 'general', 'vision', 'large-quality'],
    recommendedUse: 'Kimi K2.6 via OpenRouter when you want Moonshot quality without downloading ~350GB offline shards.',
    requiresApiKey: true, apiKeyUrl: 'https://openrouter.ai/keys',
  },
  {
    id: 'openrouter-glm-5.2', provider: 'openrouter', providerName: 'OpenRouter', modelId: 'z-ai/glm-5.2',
    name: 'GLM-5.2', tier: 'premium', speed: 'Provider dependent', quality: 'Frontier agentic',
    categories: ['coding', 'general', 'math', 'business', 'large-quality'],
    recommendedUse: 'Z.ai GLM-5.2 via OpenRouter — long-horizon coding/agents, large context. Best practical way to use GLM-5.2 without a cluster.',
    requiresApiKey: true, apiKeyUrl: 'https://openrouter.ai/keys',
  },
  {
    id: 'openrouter-qwen3-coder-480b', provider: 'openrouter', providerName: 'OpenRouter', modelId: 'qwen/qwen3-coder',
    name: 'Qwen3 Coder (online)', tier: 'premium', speed: 'Provider dependent', quality: 'Flagship coding',
    categories: ['coding', 'large-quality'],
    recommendedUse: 'Qwen3 Coder via OpenRouter for agentic coding without downloading the 480B MoE GGUF.',
    requiresApiKey: true, apiKeyUrl: 'https://openrouter.ai/keys',
  },
  {
    id: 'openrouter-llama4-maverick', provider: 'openrouter', providerName: 'OpenRouter', modelId: 'meta-llama/llama-4-maverick',
    name: 'Llama 4 Maverick (online)', tier: 'premium', speed: 'Provider dependent', quality: 'Native multimodal MoE',
    categories: ['vision', 'coding', 'general', 'large-quality'],
    recommendedUse: 'Meta Llama 4 Maverick via OpenRouter — early-fusion vision + MoE without ~151GB offline download.',
    requiresApiKey: true, apiKeyUrl: 'https://openrouter.ai/keys',
  },
  {
    id: 'openrouter-llama-405b', provider: 'openrouter', providerName: 'OpenRouter', modelId: 'meta-llama/llama-3.1-405b-instruct',
    name: 'Llama 3.1 405B Instruct', tier: 'premium', speed: 'Provider dependent', quality: 'Frontier',
    categories: ['general', 'coding', 'math', 'business', 'writing', 'large-quality'],
    recommendedUse: 'Frontier 405B-class chat/reasoning through OpenRouter without hosting weights locally.',
    requiresApiKey: true, apiKeyUrl: 'https://openrouter.ai/keys',
  },
  {
    id: 'openrouter-gpt-4o', provider: 'openrouter', providerName: 'OpenRouter', modelId: 'openai/gpt-4o',
    name: 'GPT-4o', tier: 'premium', speed: 'Fast', quality: 'Frontier',
    categories: ['general', 'coding', 'business', 'writing', 'vision', 'large-quality'],
    recommendedUse: 'OpenAI GPT-4o via OpenRouter for high-quality chat, coding, and vision-capable workflows.',
    requiresApiKey: true, apiKeyUrl: 'https://openrouter.ai/keys',
  },
  {
    id: 'openrouter-gpt-4.1', provider: 'openrouter', providerName: 'OpenRouter', modelId: 'openai/gpt-4.1',
    name: 'GPT-4.1', tier: 'premium', speed: 'Fast', quality: 'Frontier',
    categories: ['general', 'coding', 'business', 'writing', 'vision', 'large-quality'],
    recommendedUse: 'OpenAI GPT-4.1 via OpenRouter for strong instruction following, coding, and vision.',
    requiresApiKey: true, apiKeyUrl: 'https://openrouter.ai/keys',
  },
  {
    id: 'openrouter-claude-opus', provider: 'openrouter', providerName: 'OpenRouter', modelId: 'anthropic/claude-opus-4',
    name: 'Claude Opus via OpenRouter', tier: 'premium', speed: 'Provider dependent', quality: 'Frontier',
    categories: ['general', 'coding', 'business', 'writing', 'vision', 'large-quality'],
    recommendedUse: 'Anthropic Opus-class reasoning and vision through OpenRouter for complex planning and coding.',
    requiresApiKey: true, apiKeyUrl: 'https://openrouter.ai/keys',
  },
  {
    id: 'openrouter-deepseek-v3', provider: 'openrouter', providerName: 'OpenRouter', modelId: 'deepseek/deepseek-chat-v3-0324',
    name: 'DeepSeek V3', tier: 'premium', speed: 'Provider dependent', quality: 'Frontier MoE',
    categories: ['coding', 'math', 'general', 'large-quality'],
    recommendedUse: 'DeepSeek V3 via OpenRouter for strong coding and reasoning at frontier scale.',
    requiresApiKey: true, apiKeyUrl: 'https://openrouter.ai/keys',
  },
  {
    id: 'openrouter-command-r-plus', provider: 'openrouter', providerName: 'OpenRouter', modelId: 'cohere/command-r-plus',
    name: 'Command R+', tier: 'premium', speed: 'Provider dependent', quality: 'Enterprise RAG',
    categories: ['general', 'business', 'writing', 'large-quality'],
    recommendedUse: 'Cohere Command R+ for long-context RAG and enterprise assistant workflows.',
    requiresApiKey: true, apiKeyUrl: 'https://openrouter.ai/keys',
  },
  {
    id: 'together-llama-405b', provider: 'together', providerName: 'Together AI', modelId: 'meta-llama/Meta-Llama-3.1-405B-Instruct-Turbo',
    name: 'Llama 3.1 405B Turbo', tier: 'premium', speed: 'Fast', quality: 'Frontier',
    categories: ['general', 'coding', 'business', 'large-quality'],
    recommendedUse: 'Hosted 405B-class inference on Together AI without local multi-GPU hardware.',
    requiresApiKey: true, apiKeyUrl: 'https://api.together.xyz/settings/api-keys',
  },
  {
    id: 'openrouter-llama-70b', provider: 'openrouter', providerName: 'OpenRouter', modelId: 'meta-llama/llama-3.3-70b-instruct',
    name: 'Llama 3.3 70B Instruct', tier: 'premium', speed: 'Provider dependent', quality: 'Very high',
    categories: ['general', 'coding', 'business', 'writing', 'large-quality'],
    recommendedUse: 'Meta 70B-class model via OpenRouter when you want Code Workspace–eligible quality without Groq.',
    requiresApiKey: true, apiKeyUrl: 'https://openrouter.ai/keys',
  },
];

export const IMAGE_GENERATION_MODELS: ImageGenerationModel[] = [
  {
    id: 'pollinations-flux', type: 'image', mode: 'online', tier: 'free', provider: 'pollinations', providerName: 'Pollinations', modelId: 'flux',
    name: 'Pollinations FLUX', categories: ['image-realistic', 'image-art', 'image-design'],
    recommendedUse: 'Free online image generation with no API key. Good for quick prototypes.', requiresApiKey: false, supportsDirectGeneration: true,
    defaultWidth: 1024, defaultHeight: 1024,
  },
  {
    id: 'pollinations-turbo', type: 'image', mode: 'online', tier: 'free', provider: 'pollinations', providerName: 'Pollinations', modelId: 'turbo',
    name: 'Pollinations Turbo', categories: ['image-design', 'image-art'],
    recommendedUse: 'Fast free online drafts, posters, thumbnails, and social creatives.', requiresApiKey: false, supportsDirectGeneration: true,
    defaultWidth: 768, defaultHeight: 768,
  },
  {
    id: 'openai-gpt-image-1', type: 'image', mode: 'online', tier: 'premium', provider: 'openai', providerName: 'OpenAI', modelId: 'gpt-image-1',
    name: 'GPT Image 1', categories: ['image-realistic', 'image-design', 'image-art'],
    recommendedUse: 'Paid OpenAI image generation. Add an OpenAI key in Control Center.', requiresApiKey: true, supportsDirectGeneration: true,
    defaultWidth: 1024, defaultHeight: 1024,
  },
  {
    id: 'hf-sdxl', type: 'image', mode: 'online', tier: 'free', provider: 'huggingface', providerName: 'Hugging Face', modelId: 'stabilityai/stable-diffusion-xl-base-1.0',
    name: 'SDXL via Hugging Face', categories: ['image-realistic', 'image-art'],
    recommendedUse: 'Hugging Face Inference API. Add a token in Control Center.', requiresApiKey: true, supportsDirectGeneration: true,
    defaultWidth: 1024, defaultHeight: 1024,
  },
  {
    id: 'together-flux-schnell', type: 'image', mode: 'online', tier: 'premium', provider: 'together', providerName: 'Together AI', modelId: 'black-forest-labs/FLUX.1-schnell',
    name: 'FLUX.1 Schnell', categories: ['image-realistic', 'image-design'],
    recommendedUse: 'Together AI FLUX. Add a Together key in Control Center.', requiresApiKey: true, supportsDirectGeneration: true,
    defaultWidth: 1024, defaultHeight: 1024,
  },
  {
    id: 'stability-sdxl', type: 'image', mode: 'online', tier: 'premium', provider: 'stability', providerName: 'Stability AI', modelId: 'stable-image-core',
    name: 'Stability Image Core', categories: ['image-realistic', 'image-design'],
    recommendedUse: 'Stability AI core generate. Add a Stability key in Control Center.', requiresApiKey: true, supportsDirectGeneration: true,
    defaultWidth: 1024, defaultHeight: 1024,
  },
  {
    id: 'replicate-flux-dev', type: 'image', mode: 'online', tier: 'premium', provider: 'replicate', providerName: 'Replicate', modelId: 'black-forest-labs/flux-schnell',
    name: 'FLUX via Replicate', categories: ['image-realistic', 'image-design'],
    recommendedUse: 'Replicate hosted FLUX. Add a Replicate token in Control Center.', requiresApiKey: true, supportsDirectGeneration: true,
    defaultWidth: 1024, defaultHeight: 1024,
  },
];
